# Configuración mínima para Apache Pulsar
# Solo proxy y manager (broker)

# Componentes principales
components:
  # Habilitar solo los componentes esenciales
  zookeeper: true
  bookkeeper: true
  broker: true
  proxy: true
  
  # Habilitar Pulsar Manager para interfaz web
  pulsar_manager: true
  
  # Deshabilitar componentes de monitoring y otros
  functions: false
  toolset: false

# Deshabilitar todos los componentes de monitoring
monitoring:
  prometheus: false
  grafana: false
  node_exporter: false
  alert_manager: false

# Deshabilitar explícitamente Prometheus stack
prometheus:
  enabled: false

# Deshabilitar explícitamente Grafana
grafana:
  enabled: false

# Deshabilitar kube-state-metrics
kube-state-metrics:
  enabled: false

# Deshabilitar node exporter
prometheus-node-exporter:
  enabled: false

# Deshabilitar Victoria Metrics
victoria-metrics-k8s-stack:
  enabled: false

# Configuración de ZooKeeper (requerido para Pulsar)
zookeeper:
  replicaCount: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 0.1
  persistence:
    data:
      size: 2Gi
    log:
      size: 1Gi

# Configuración de BookKeeper (requerido para almacenamiento)
bookkeeper:
  replicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.2
  persistence:
    journal:
      size: 2Gi
    ledgers:
      size: 5Gi

# Configuración del Broker (manager de mensajes)
broker:
  replicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.2
  configData:
    managedLedgerDefaultEnsembleSize: "1"
    managedLedgerDefaultWriteQuorum: "1"
    managedLedgerDefaultAckQuorum: "1"

# Configuración del Proxy (acceso interno)
proxy:
  replicaCount: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 0.1
  service:
    type: LoadBalancer

# Configuración del Pulsar Manager (interfaz web de administración)
pulsar_manager:
  replicaCount: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 0.1
  service:
    type: ClusterIP
  
  # Configuración del Ingress para acceso web externo
  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
      external-dns.alpha.kubernetes.io/hostname: pulsar.neolabs.com.co
      external-dns.alpha.kubernetes.io/target: afe145c3-1945-467e-b776-6ee9c6bd304a.cfargotunnel.com
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: pulsar.neolabs.com.co
        paths:
          - path: /
            pathType: Prefix

# Configuración global
metadata:
  component: pulsar
  cluster: pulsar

# Configuración de imagen (usar imagen estable)
images:
  tag: 3.0.2

# Configuración de almacenamiento por defecto
default_storage:
  provisioner: kubernetes.io/no-provisioner
  type: local
  size: 5Gi
  
# Configuración de recursos por defecto más conservadora
resources:
  requests:
    memory: 128Mi
    cpu: 0.1
