apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: "#{APP_NAME}#"
  name: "#{APP_NAME}#"
  namespace: "#{AKS_NAMESPACE}#"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    app: "#{APP_NAME}#"
