cloudflare:
  tunnelName: "core"
  tunnelId: "afe145c3-1945-467e-b776-6ee9c6bd304a"
  secretName: "tunnel-credentials"
  ingress:
    - hostname: "*.neolabs.com.co"
      service: "https://ingress-nginx-controller.kube-system.svc.cluster.local:443"
      originRequest:
        noTLSVerify: true

resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

replicaCount: 1
